# -*- Makefile -*-

# Check if the "ledit" library is present.
ledit:
	@ echo 'include Ledit' > src/userInput.ml
	@ if ocamlbuild src/userInput.cmo 1> /dev/null; then		\
	  echo ' * Ledit is present: use it as UserInput.';		\
	  echo 'let use_ledit = true' > myocamlbuild_config.ml ;	\
	else								\
	  echo 'include StdUserInput' > src/userInput.ml;		\
	  echo ' * Ledit is not present: use default UserInput.';	\
	  echo 'let use_ledit = false' > myocamlbuild_config.ml ;	\
	fi

announce:
	@ echo "Source configuration ..."

configure: announce ledit
